### ISSUE TITLE
execution error message

### ISSUE THREAD

**Issue by Hanjiewu** [esteinig/sccion#4]
Installed sccion and executed using sccion type -a XXX.fasta and here are the messages:

```
[Traceback (most recent call last):
  File "/root/miniconda3/bin/sccion", line 12, in <module>
    sys.exit(terminal_client())
  File "/root/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/sccion/terminal/type/commands.py", line 42, in type
    min_identity=min_identity
  File "/root/miniconda3/lib/python3.7/site-packages/sccion/sccion.py", line 89, in type_assembly
    Species(fasta=self.fasta), 'scientific_name'
  File "/root/miniconda3/lib/python3.7/site-packages/sccion/type.py", line 165, in __init__
    header=0
  File "/root/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/root/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/root/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/root/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/root/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'/root/miniconda3/lib/python3.7/site-packages/sccion/db/staphylococci.index' does not exist: b'/root/miniconda3/lib/python3.7/site-packages/sccion/db/staphylococci.index']
```

What went wrong?

**Comment by esteinig** [comment]
@Hanjiewu my apologies, forgot to upload the correct databases. It should be working in the latest release `v0.1.a6`  (+ Anaconda)
